spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: ${DATABASE_URL_HONCARI:jdbc:postgresql://localhost:5432/honcari}
      username: ${DATABASE_USER:postgres}
      password: ${DATABASE_PASSWORD:postgres}
  mail:
    host: smtp.gmail.com
    port: 587
    username: honcari.web@gmail.com
    password: tdrfpzcsqedgkbre
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true    


cloud:
  aws:
    credentials:
      accessKey: "AWS_ACCESS_KEY"
      secretKey: "AWS_SECRET_KEY"
      profileName:
      instanceProfile: false
    stack:
      auto: false
    region:
      auto: false
      static: ap-northeast-1
      